### ISSUE TITLE
Question: Layout for Esc/~/cmd

### ISSUE THREAD

**Issue by wfendler** [ravicious/TADA68#1]
I was unable to remap alt -> cmd myself in the online editor but your FLASH.BIN file worked great. I have a couple questions about this:

+ How did you remap alt -> cmd and win -> opt?
+ What was the reason for mapping esc to ``/~`?
+ Where did esc go? The ``/~` key on the top right corner doesn't currently seem to do anything.

Thanks for posting! This was all super helpful getting things up and running for me.

**Comment by ravicious** [comment]
Hey, I'm glad you found this repo useful.

1. What problems did you have? If I remember correctly, I clicked on Win and chose Alt and then clicked on Alt and chose Win to swap them.
2. I mapped Esc to that key because my Caps Lock acts as Esc when pressed alone and as Ctrl when pressed in combination with another key. I didn't remap Caps Lock to Esc on TADA68 because I already have software mapping through Karabiner and BetterTouchTool which assumes that the Caps Lock key is a Caps Lock key.
3. I guess I answered this in the previous point. 😉 I'm used to having tilde and backtick under one key so that's why I have it there.

If you'd like to take my config and customize it, then you can use [a direct link to the editor with my setup](http://123.57.250.164:3000/tada68#A86DC13F8C670AD9684521480830D94D). Each of [the releases](https://github.com/ravicious/TADA68/releases) has it in its description, but it's just not something that I mentioned in the README. I probably should add that since 32 people already starred this repo. 😶

Does that answer your questions?
